title: Jason Pizzollo
logo: "/images/photo.jpg?raw=true"
description: >
  Data Scientist
  <br>
  Genomics Ph.D.
  <br><br>
  <i class="fab fa-github" style="color:#000000"></i>
  <a href="https://github.com/jpizzollo/">GitHub</a>
  <br>
  <i class="fab fa-linkedin" style="color:#2867B2"></i>
  <a href="https://www.linkedin.com/in/jasonpizzollo/">LinkedIn</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
